<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="subscriptions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="podcast" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:attribute name="title" type="xs:string" use="required" />
            <xs:attribute name="scope">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="all"/>
                  <xs:enumeration value="latest"/>
                  <xs:enumeration value="none"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="url" type="xs:anyURI" use="required" />
            <xs:attribute name="day">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="Daily"/>
                  <xs:enumeration value="Mon"/>
                  <xs:enumeration value="Tue"/>
                  <xs:enumeration value="Wed"/>
                  <xs:enumeration value="Thu"/>
                  <xs:enumeration value="Fri"/>
                  <xs:enumeration value="Sat"/>
                  <xs:enumeration value="Sun"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="pull_time">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="00"/><xs:enumeration value="01"/>
                  <xs:enumeration value="02"/><xs:enumeration value="03"/>
                  <xs:enumeration value="04"/><xs:enumeration value="05"/>
                  <xs:enumeration value="06"/><xs:enumeration value="07"/>
                  <xs:enumeration value="08"/><xs:enumeration value="09"/>
                  <xs:enumeration value="10"/><xs:enumeration value="11"/>
                  <xs:enumeration value="12"/><xs:enumeration value="13"/>
                  <xs:enumeration value="14"/><xs:enumeration value="15"/>
                  <xs:enumeration value="16"/><xs:enumeration value="17"/>
                  <xs:enumeration value="18"/><xs:enumeration value="19"/>
                  <xs:enumeration value="20"/><xs:enumeration value="21"/>
                  <xs:enumeration value="22"/><xs:enumeration value="23"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
