# policy/ast.rego
#
# Code style and architecture policy enforced over the clang AST JSON
# (ast.json, generated by scripts/gen_ast.sh).
#
# Rules enforced:
#   1. khtml/kxml split   — khtml calls only in render_shell
#   2. malloc isolation   — malloc only in write_feeds_xml (temp path)
#   3. Renderer coverage  — all render_* functions must call kxml
#   4. khttp_free absent  — render helpers must not call khttp_free
#   5. goto discipline    — main() uses only the 'done' label
#
# Usage:
#   conftest test --policy policy/ ast.json
#   opa eval -d policy/ast.rego -i ast.json 'data.podcast_mgr.ast.violations'
#
package podcast_mgr.ast

import rego.v1

# ── helpers ──────────────────────────────────────────────────────────────

fn_by_name(name) := fn if {
    some fn in input.functions
    fn.name == name
}

renderer_functions := {fn.name |
    some fn in input.functions
    startswith(fn.name, "render_")
}

# ── Rule 1: khtml/kxml split ─────────────────────────────────────────────
# khtml calls are NOT permitted anywhere — render_shell uses khttp_puts
# directly to avoid buffering/ordering issues when mixing khtml and
# khttp_puts in the same scope.
# All render_* functions must use kxml (except render_shell which is raw).

deny contains msg if {
    some fn in input.functions
    count(fn.khtml_calls) > 0
    msg := sprintf(
        "khtml violation: '%s' calls khtml functions %v — khtml must not be used (render_shell uses khttp_puts directly)",
        [fn.name, fn.khtml_calls]
    )
}

# ── Rule 2: malloc isolation ─────────────────────────────────────────────
# malloc is permitted only in write_feeds_xml (temp path allocation).
# All other functions must use arena_alloc.

deny contains msg if {
    some fn in input.functions
    fn.name != "write_feeds_xml"
    fn.calls_malloc == true
    msg := sprintf(
        "malloc violation: '%s' calls malloc — use arena_alloc instead (malloc only permitted in write_feeds_xml for temp path)",
        [fn.name]
    )
}

# ── Rule 3: renderer coverage ─────────────────────────────────────────────
# Every render_* function (except render_shell) must call at least one kxml function.

deny contains msg if {
    some name in renderer_functions
    name != "render_shell"
    fn := fn_by_name(name)
    count(fn.kxml_calls) == 0
    msg := sprintf(
        "renderer coverage: '%s' does not call any kxml function — all render_* except render_shell must use kxml",
        [name]
    )
}

# ── Rule 4: khttp_free not in render helpers ──────────────────────────────
# khttp_free is a request lifecycle call — it belongs in the dispatch loop
# in main(), not in render helpers.

deny contains msg if {
    some fn in input.functions
    startswith(fn.name, "render_")
    fn.calls_khttp_free == true
    msg := sprintf(
        "lifecycle violation: '%s' calls khttp_free — request teardown belongs in the main() dispatch loop only",
        [fn.name]
    )
}

# ── Rule 5: goto discipline ───────────────────────────────────────────────
# main() must use only the 'done' label for early exits.
# Other functions must not use goto at all.

deny contains msg if {
    fn := fn_by_name("main")
    some label in fn.goto_labels
    label != "done"
    msg := sprintf(
        "goto discipline: main() uses goto label '%s' — only 'done' is permitted",
        [label]
    )
}

deny contains msg if {
    some fn in input.functions
    fn.name != "main"
    count(fn.goto_labels) > 0
    msg := sprintf(
        "goto discipline: '%s' uses goto labels %v — goto is only permitted in main() for the done: exit path",
        [fn.name, fn.goto_labels]
    )
}

# ── Summary ───────────────────────────────────────────────────────────────

violations := deny

allow if count(deny) == 0
